apiVersion: v2
name: castai-evictor
description: Cluster utilization defragmentation tool
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.31.24
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: 0c2182e4e1ba605c9f4ceaa8d9f320a5db631cad
annotations:
  release-date: "2025-01-20T08:55:21"
# GitHub actions fails when 'chart' directory is used for dependencies.
dependencies:
  - name: castai-evictor-ext
    repository: file://child-charts/castai-evictor-ext
    version: 0.1.0
    condition: castai-evictor-ext.enabled
